name: Bump version

on:
  release:
    types: [created]

env:
  NEW_VERSION: ${{ env.GITHUB_REF }}

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bump version
      run: |
        NEW_VERSION=${{ env.NEW_VERSION }}
        echo "Bumping version to $NEW_VERSION"
        sed -i "s/version='.*'/version='$NEW_VERSION'/" setup.cfg
        git diff

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump version to $NEW_VERSION
        branch: main

